default_context:
  project_name: 'FastAPI_Project'
  project_slug: 'fastapi_project'
  domain_main: 'fastapi_project.com'
  domain_staging: 'stag.fastapi_project.com'
  docker_swarm_stack_name_main: 'fastapi_project-com'
  docker_swarm_stack_name_staging: 'stag-fastapi_project-com'
  secret_key: '532d272256b0a190c5751c1e14491affe0987cce14187c7fa4ef6f578eb53435'
  first_superuser: 'admin@fastapi_project.com'
  first_superuser_password: 'ee339405553254cefd22187cbc5cab59e8658500773527c72bc57c43a1669a6a'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastapi_project.com", "https://stag.fastapi_project.com", "https://fastapi_project.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: 'mailuser'
  smtp_password: 'fdf9558f554d89ad1422c86ef0ff9a218df745595e3b1c92090cb5809d38f3c0'
  smtp_emails_from_email: 'info@fastapi_project.com'
  postgres_password: '6b88d3536da0367c768dcd17b1cc3752e077029cb348c299063bdaf109a70e5c'
  pgadmin_default_user: 'admin@fastapi_project.com'
  pgadmin_default_user_password: 'ee339405553254cefd22187cbc5cab59e8658500773527c72bc57c43a1669a6a'
  traefik_constraint_tag: 'fastapi_project.com'
  traefik_constraint_tag_staging: 'stag.fastapi_project.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:ee339405553254cefd22187cbc5cab59e8658500773527c72bc57c43a1669a6a'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
